version: '3.9'

services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "8081:80"
    networks:
      - app-network
    restart: always

  backend:
    build:
      context: ./backend
    ports:
      - "5001:5000"
    networks:
      - app-network
    environment:
      - FLASK_APP=main.py
      - FLASK_ENV=development
      - FLASK_DEBUG=1
    restart: always

networks:
  app-network:
    driver: bridge